version: '3.8'

services:
  web:
    build: ./src
    volumes:
      - ./src/:/usr/src/app
    ports:
      - 8002:8000
    environment:
      - DATABASE_URL=mysql+pymysql://root:root@db:3306/confwms
      - TESTING_DATABASE_URL=mysql+pymysql://root:root@db:3306/test
    depends_on:
      - db

  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=conf-wms
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
  mysql_config:
