"""auto-generated migration

Revision ID: 396e1b61f9d5
Revises: 89a464d3a185
Create Date: 2023-07-18 16:29:43.545712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '396e1b61f9d5'
down_revision = '89a464d3a185'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conferenceeditors', sa.Column('conference_id', sa.BigInteger(), nullable=False))
    op.add_column('conferenceeditors', sa.Column('editor_id', sa.BigInteger(), nullable=False))
    op.drop_constraint('conferenceeditors_conferenceID_fkey', 'conferenceeditors', type_='foreignkey')
    op.drop_constraint('conferenceeditors_editorID_fkey', 'conferenceeditors', type_='foreignkey')
    op.create_foreign_key(None, 'conferenceeditors', 'conference', ['conference_id'], ['id'])
    op.create_foreign_key(None, 'conferenceeditors', 'user', ['editor_id'], ['id'])
    op.drop_column('conferenceeditors', 'editorID')
    op.drop_column('conferenceeditors', 'conferenceID')
    op.add_column('conferenceroster', sa.Column('conference_id', sa.BigInteger(), nullable=False))
    op.add_column('conferenceroster', sa.Column('author_id', sa.BigInteger(), nullable=False))
    op.drop_constraint('conferenceroster_authorID_fkey', 'conferenceroster', type_='foreignkey')
    op.drop_constraint('conferenceroster_conferenceID_fkey', 'conferenceroster', type_='foreignkey')
    op.create_foreign_key(None, 'conferenceroster', 'user', ['author_id'], ['id'])
    op.create_foreign_key(None, 'conferenceroster', 'conference', ['conference_id'], ['id'])
    op.drop_column('conferenceroster', 'authorID')
    op.drop_column('conferenceroster', 'conferenceID')
    op.drop_constraint('paper_authorID_fkey', 'paper', type_='foreignkey')
    op.create_foreign_key(None, 'paper', 'conferenceroster', ['authorID'], ['id'])
    op.drop_constraint('paperrevisions_paperID_fkey', 'paperrevisions', type_='foreignkey')
    op.create_foreign_key(None, 'paperrevisions', 'submittedpapers', ['paperID'], ['id'])
    op.add_column('review', sa.Column('editor_id', sa.BigInteger(), nullable=False))
    op.add_column('review', sa.Column('associate_editor_id', sa.BigInteger(), nullable=False))
    op.add_column('review', sa.Column('reviewer_id', sa.BigInteger(), nullable=False))
    op.add_column('review', sa.Column('revision_id', sa.BigInteger(), nullable=False))
    op.drop_constraint('review_editorID_fkey', 'review', type_='foreignkey')
    op.drop_constraint('review_revisionID_fkey', 'review', type_='foreignkey')
    op.drop_constraint('review_associate_editorID_fkey', 'review', type_='foreignkey')
    op.drop_constraint('review_reviewerID_fkey', 'review', type_='foreignkey')
    op.create_foreign_key(None, 'review', 'conferencereviewer', ['reviewer_id'], ['id'])
    op.create_foreign_key(None, 'review', 'conferenceassociateeditors', ['associate_editor_id'], ['id'])
    op.create_foreign_key(None, 'review', 'conferenceeditors', ['editor_id'], ['id'])
    op.create_foreign_key(None, 'review', 'paperrevisions', ['revision_id'], ['id'])
    op.drop_column('review', 'reviewerID')
    op.drop_column('review', 'editorID')
    op.drop_column('review', 'revisionID')
    op.drop_column('review', 'associate_editorID')
    op.add_column('submittedpapers', sa.Column('submission_id', sa.BigInteger(), nullable=False))
    op.drop_constraint('submittedpapers_paperID_fkey', 'submittedpapers', type_='foreignkey')
    op.drop_constraint('submittedpapers_submissionID_fkey', 'submittedpapers', type_='foreignkey')
    op.create_foreign_key(None, 'submittedpapers', 'submission', ['submission_id'], ['id'])
    op.drop_column('submittedpapers', 'submissionID')
    op.drop_column('submittedpapers', 'paperID')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submittedpapers', sa.Column('paperID', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('submittedpapers', sa.Column('submissionID', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'submittedpapers', type_='foreignkey')
    op.create_foreign_key('submittedpapers_submissionID_fkey', 'submittedpapers', 'submission', ['submissionID'], ['id'])
    op.create_foreign_key('submittedpapers_paperID_fkey', 'submittedpapers', 'paper', ['paperID'], ['id'])
    op.drop_column('submittedpapers', 'submission_id')
    op.add_column('review', sa.Column('associate_editorID', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('review', sa.Column('revisionID', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('review', sa.Column('editorID', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('review', sa.Column('reviewerID', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.create_foreign_key('review_reviewerID_fkey', 'review', 'user', ['reviewerID'], ['id'])
    op.create_foreign_key('review_associate_editorID_fkey', 'review', 'user', ['associate_editorID'], ['id'])
    op.create_foreign_key('review_revisionID_fkey', 'review', 'paperrevisions', ['revisionID'], ['id'])
    op.create_foreign_key('review_editorID_fkey', 'review', 'user', ['editorID'], ['id'])
    op.drop_column('review', 'revision_id')
    op.drop_column('review', 'reviewer_id')
    op.drop_column('review', 'associate_editor_id')
    op.drop_column('review', 'editor_id')
    op.drop_constraint(None, 'paperrevisions', type_='foreignkey')
    op.create_foreign_key('paperrevisions_paperID_fkey', 'paperrevisions', 'paper', ['paperID'], ['id'])
    op.drop_constraint(None, 'paper', type_='foreignkey')
    op.create_foreign_key('paper_authorID_fkey', 'paper', 'user', ['authorID'], ['id'])
    op.add_column('conferenceroster', sa.Column('conferenceID', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('conferenceroster', sa.Column('authorID', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'conferenceroster', type_='foreignkey')
    op.drop_constraint(None, 'conferenceroster', type_='foreignkey')
    op.create_foreign_key('conferenceroster_conferenceID_fkey', 'conferenceroster', 'conference', ['conferenceID'], ['id'])
    op.create_foreign_key('conferenceroster_authorID_fkey', 'conferenceroster', 'user', ['authorID'], ['id'])
    op.drop_column('conferenceroster', 'author_id')
    op.drop_column('conferenceroster', 'conference_id')
    op.add_column('conferenceeditors', sa.Column('conferenceID', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('conferenceeditors', sa.Column('editorID', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'conferenceeditors', type_='foreignkey')
    op.drop_constraint(None, 'conferenceeditors', type_='foreignkey')
    op.create_foreign_key('conferenceeditors_editorID_fkey', 'conferenceeditors', 'user', ['editorID'], ['id'])
    op.create_foreign_key('conferenceeditors_conferenceID_fkey', 'conferenceeditors', 'conference', ['conferenceID'], ['id'])
    op.drop_column('conferenceeditors', 'editor_id')
    op.drop_column('conferenceeditors', 'conference_id')
    # ### end Alembic commands ###
