"""auto-generated migration

Revision ID: 46fb6cedb1fd
Revises: 396e1b61f9d5
Create Date: 2023-07-19 12:37:10.309182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46fb6cedb1fd'
down_revision = '396e1b61f9d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conferenceassociateeditors', sa.Column('conference_id', sa.BigInteger(), nullable=False))
    op.add_column('conferenceassociateeditors', sa.Column('associate_editor_id', sa.BigInteger(), nullable=False))
    op.drop_constraint('conferenceassociateeditors_associate_editorID_fkey', 'conferenceassociateeditors', type_='foreignkey')
    op.drop_constraint('conferenceassociateeditors_conferenceID_fkey', 'conferenceassociateeditors', type_='foreignkey')
    op.create_foreign_key(None, 'conferenceassociateeditors', 'user', ['associate_editor_id'], ['id'])
    op.create_foreign_key(None, 'conferenceassociateeditors', 'conference', ['conference_id'], ['id'])
    op.drop_column('conferenceassociateeditors', 'associate_editorID')
    op.drop_column('conferenceassociateeditors', 'conferenceID')
    op.add_column('conferencereviewer', sa.Column('conference_id', sa.BigInteger(), nullable=False))
    op.add_column('conferencereviewer', sa.Column('reviewer_id', sa.BigInteger(), nullable=False))
    op.drop_constraint('conferencereviewer_conferenceID_fkey', 'conferencereviewer', type_='foreignkey')
    op.drop_constraint('conferencereviewer_reviewerID_fkey', 'conferencereviewer', type_='foreignkey')
    op.create_foreign_key(None, 'conferencereviewer', 'conference', ['conference_id'], ['id'])
    op.create_foreign_key(None, 'conferencereviewer', 'user', ['reviewer_id'], ['id'])
    op.drop_column('conferencereviewer', 'reviewerID')
    op.drop_column('conferencereviewer', 'conferenceID')
    op.add_column('event', sa.Column('conference_id', sa.BigInteger(), nullable=False))
    op.drop_constraint('event_conferenceID_fkey', 'event', type_='foreignkey')
    op.create_foreign_key(None, 'event', 'conference', ['conference_id'], ['id'])
    op.drop_column('event', 'conferenceID')
    op.add_column('paper', sa.Column('author_id', sa.BigInteger(), nullable=False))
    op.drop_constraint('paper_authorID_fkey', 'paper', type_='foreignkey')
    op.create_foreign_key(None, 'paper', 'conferenceroster', ['author_id'], ['author_id'])
    op.drop_column('paper', 'authorID')
    op.add_column('paperrevisions', sa.Column('paper_id', sa.BigInteger(), nullable=False))
    op.add_column('paperrevisions', sa.Column('submission_id', sa.BigInteger(), nullable=True))
    op.drop_constraint('paperrevisions_paperID_fkey', 'paperrevisions', type_='foreignkey')
    op.create_foreign_key(None, 'paperrevisions', 'paper', ['paper_id'], ['id'])
    op.create_foreign_key(None, 'paperrevisions', 'submittedpapers', ['submission_id'], ['submission_id'])
    op.drop_column('paperrevisions', 'submissionID')
    op.drop_column('paperrevisions', 'paperID')
    op.add_column('paperstatus', sa.Column('paper_id', sa.BigInteger(), nullable=False))
    op.drop_constraint('paperstatus_paperID_fkey', 'paperstatus', type_='foreignkey')
    op.create_foreign_key(None, 'paperstatus', 'paper', ['paper_id'], ['id'])
    op.drop_column('paperstatus', 'paperID')
    op.drop_constraint('review_associate_editor_id_fkey', 'review', type_='foreignkey')
    op.drop_constraint('review_editor_id_fkey', 'review', type_='foreignkey')
    op.drop_constraint('review_reviewer_id_fkey', 'review', type_='foreignkey')
    op.create_foreign_key(None, 'review', 'conferencereviewer', ['reviewer_id'], ['reviewer_id'])
    op.create_foreign_key(None, 'review', 'conferenceeditors', ['editor_id'], ['editor_id'])
    op.create_foreign_key(None, 'review', 'conferenceassociateeditors', ['associate_editor_id'], ['associate_editor_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.create_foreign_key('review_reviewer_id_fkey', 'review', 'conferencereviewer', ['reviewer_id'], ['id'])
    op.create_foreign_key('review_editor_id_fkey', 'review', 'conferenceeditors', ['editor_id'], ['id'])
    op.create_foreign_key('review_associate_editor_id_fkey', 'review', 'conferenceassociateeditors', ['associate_editor_id'], ['id'])
    op.add_column('paperstatus', sa.Column('paperID', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'paperstatus', type_='foreignkey')
    op.create_foreign_key('paperstatus_paperID_fkey', 'paperstatus', 'paper', ['paperID'], ['id'])
    op.drop_column('paperstatus', 'paper_id')
    op.add_column('paperrevisions', sa.Column('paperID', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('paperrevisions', sa.Column('submissionID', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'paperrevisions', type_='foreignkey')
    op.drop_constraint(None, 'paperrevisions', type_='foreignkey')
    op.create_foreign_key('paperrevisions_paperID_fkey', 'paperrevisions', 'submittedpapers', ['paperID'], ['id'])
    op.drop_column('paperrevisions', 'submission_id')
    op.drop_column('paperrevisions', 'paper_id')
    op.add_column('paper', sa.Column('authorID', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'paper', type_='foreignkey')
    op.create_foreign_key('paper_authorID_fkey', 'paper', 'conferenceroster', ['authorID'], ['id'])
    op.drop_column('paper', 'author_id')
    op.add_column('event', sa.Column('conferenceID', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.create_foreign_key('event_conferenceID_fkey', 'event', 'conference', ['conferenceID'], ['id'])
    op.drop_column('event', 'conference_id')
    op.add_column('conferencereviewer', sa.Column('conferenceID', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('conferencereviewer', sa.Column('reviewerID', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'conferencereviewer', type_='foreignkey')
    op.drop_constraint(None, 'conferencereviewer', type_='foreignkey')
    op.create_foreign_key('conferencereviewer_reviewerID_fkey', 'conferencereviewer', 'user', ['reviewerID'], ['id'])
    op.create_foreign_key('conferencereviewer_conferenceID_fkey', 'conferencereviewer', 'conference', ['conferenceID'], ['id'])
    op.drop_column('conferencereviewer', 'reviewer_id')
    op.drop_column('conferencereviewer', 'conference_id')
    op.add_column('conferenceassociateeditors', sa.Column('conferenceID', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('conferenceassociateeditors', sa.Column('associate_editorID', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'conferenceassociateeditors', type_='foreignkey')
    op.drop_constraint(None, 'conferenceassociateeditors', type_='foreignkey')
    op.create_foreign_key('conferenceassociateeditors_conferenceID_fkey', 'conferenceassociateeditors', 'conference', ['conferenceID'], ['id'])
    op.create_foreign_key('conferenceassociateeditors_associate_editorID_fkey', 'conferenceassociateeditors', 'user', ['associate_editorID'], ['id'])
    op.drop_column('conferenceassociateeditors', 'associate_editor_id')
    op.drop_column('conferenceassociateeditors', 'conference_id')
    # ### end Alembic commands ###
