"""auto-generated migration

Revision ID: 89a464d3a185
Revises: c305be501996
Create Date: 2023-07-17 13:29:28.857727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89a464d3a185'
down_revision = 'c305be501996'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviewcomments', sa.Column('review_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'reviewcomments', 'review', ['review_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviewcomments', type_='foreignkey')
    op.drop_column('reviewcomments', 'review_id')
    # ### end Alembic commands ###
