"""auto-generated migration

Revision ID: c305be501996
Revises: 
Create Date: 2023-07-17 12:30:01.079243

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c305be501996'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institution',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('contactno', sa.String(length=10), nullable=False),
    sa.Column('membership', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('reviewcomments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('comment_datetime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comment_datetime')
    )
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('contactno', sa.String(length=15), nullable=False),
    sa.Column('title', postgresql.ENUM('Mr.', 'Ms.', 'Mrs.', 'Dr.', name='user_title_enum'), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', postgresql.ENUM('SuperAdmin', 'Admin', 'Coordinator', 'Editor', 'AssociateEditor', 'Reviewer', 'Author', name='user_role_enum'), nullable=True),
    sa.Column('institution_id', sa.BigInteger(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institution.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contactno'),
    sa.UniqueConstraint('email')
    )
    op.create_table('conference',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('conference_theme', sa.String(length=255), nullable=False),
    sa.Column('in_charge', sa.BigInteger(), nullable=False),
    sa.Column('conference_track', sa.String(length=225), nullable=False),
    sa.Column('chair_name', sa.String(length=225), nullable=False),
    sa.Column('chair_designation', sa.String(length=225), nullable=False),
    sa.Column('co_chair_name', sa.String(length=225), nullable=False),
    sa.Column('conference_board', sa.String(length=225), nullable=False),
    sa.Column('organizing_committee', sa.String(length=225), nullable=False),
    sa.Column('international_advisory_board', sa.String(length=225), nullable=False),
    sa.Column('editor', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['editor'], ['user.id'], ),
    sa.ForeignKeyConstraint(['in_charge'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chair_designation'),
    sa.UniqueConstraint('chair_name'),
    sa.UniqueConstraint('co_chair_name'),
    sa.UniqueConstraint('conference_board'),
    sa.UniqueConstraint('conference_track'),
    sa.UniqueConstraint('international_advisory_board'),
    sa.UniqueConstraint('organizing_committee')
    )
    op.create_table('paper',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('paper_name', sa.String(length=225), nullable=False),
    sa.Column('authorID', sa.BigInteger(), nullable=False),
    sa.Column('abstract', sa.String(length=225), nullable=False),
    sa.Column('fullpaper', sa.String(length=225), nullable=False),
    sa.ForeignKeyConstraint(['authorID'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abstract'),
    sa.UniqueConstraint('fullpaper'),
    sa.UniqueConstraint('paper_name')
    )
    op.create_table('conferenceassociateeditors',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('conferenceID', sa.BigInteger(), nullable=False),
    sa.Column('associate_editorID', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['associate_editorID'], ['user.id'], ),
    sa.ForeignKeyConstraint(['conferenceID'], ['conference.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conferenceeditors',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('conferenceID', sa.BigInteger(), nullable=False),
    sa.Column('editorID', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['conferenceID'], ['conference.id'], ),
    sa.ForeignKeyConstraint(['editorID'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conferencereviewer',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('conferenceID', sa.BigInteger(), nullable=False),
    sa.Column('reviewerID', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['conferenceID'], ['conference.id'], ),
    sa.ForeignKeyConstraint(['reviewerID'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conferenceroster',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('conferenceID', sa.BigInteger(), nullable=False),
    sa.Column('authorID', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['authorID'], ['user.id'], ),
    sa.ForeignKeyConstraint(['conferenceID'], ['conference.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('venue', sa.Text(), nullable=False),
    sa.Column('reg_open', sa.DateTime(), nullable=False),
    sa.Column('reg_close', sa.DateTime(), nullable=False),
    sa.Column('event_start', sa.DateTime(), nullable=False),
    sa.Column('event_end', sa.Text(), nullable=False),
    sa.Column('max_participants', sa.BigInteger(), nullable=False),
    sa.Column('conferenceID', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['conferenceID'], ['conference.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_start'),
    sa.UniqueConstraint('reg_close'),
    sa.UniqueConstraint('reg_open')
    )
    op.create_table('paperrevisions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('paperID', sa.BigInteger(), nullable=False),
    sa.Column('revision_no', sa.BigInteger(), nullable=False),
    sa.Column('revision_link', sa.String(length=225), nullable=False),
    sa.Column('revision_date_time', sa.DateTime(), nullable=False),
    sa.Column('submissionID', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['paperID'], ['paper.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('revision_date_time'),
    sa.UniqueConstraint('revision_link')
    )
    op.create_table('paperstatus',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('paperID', sa.BigInteger(), nullable=False),
    sa.Column('is_final_revision', sa.Boolean(), nullable=False),
    sa.Column('to_publish', sa.Boolean(), nullable=False),
    sa.Column('presentation_status', postgresql.ENUM('Accept', 'Reject', 'Soft Accept', 'Soft Reject', name='presentation_status_enum'), nullable=True),
    sa.ForeignKeyConstraint(['paperID'], ['paper.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submission',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('journals', sa.String(length=255), nullable=False),
    sa.Column('plag_policy', sa.BigInteger(), nullable=False),
    sa.Column('sample_paper', sa.String(length=225), nullable=False),
    sa.Column('submission_deadline', sa.DateTime(), nullable=False),
    sa.Column('submission_type', postgresql.ENUM('Abstract', 'Full Paper', name='submission_type_enum'), nullable=False),
    sa.Column('conferenceID', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['conferenceID'], ['conference.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sample_paper'),
    sa.UniqueConstraint('submission_deadline')
    )
    op.create_table('review',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('editorID', sa.BigInteger(), nullable=False),
    sa.Column('associate_editorID', sa.BigInteger(), nullable=False),
    sa.Column('reviewerID', sa.BigInteger(), nullable=False),
    sa.Column('revisionID', sa.BigInteger(), nullable=False),
    sa.Column('process', postgresql.ENUM('Single Blind', 'Double Blind', name='review_process_enum'), nullable=True),
    sa.ForeignKeyConstraint(['associate_editorID'], ['user.id'], ),
    sa.ForeignKeyConstraint(['editorID'], ['user.id'], ),
    sa.ForeignKeyConstraint(['reviewerID'], ['user.id'], ),
    sa.ForeignKeyConstraint(['revisionID'], ['paperrevisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submittedpapers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('submissionID', sa.BigInteger(), nullable=False),
    sa.Column('paperID', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['paperID'], ['paper.id'], ),
    sa.ForeignKeyConstraint(['submissionID'], ['submission.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submittedpapers')
    op.drop_table('review')
    op.drop_table('submission')
    op.drop_table('paperstatus')
    op.drop_table('paperrevisions')
    op.drop_table('event')
    op.drop_table('conferenceroster')
    op.drop_table('conferencereviewer')
    op.drop_table('conferenceeditors')
    op.drop_table('conferenceassociateeditors')
    op.drop_table('paper')
    op.drop_table('conference')
    op.drop_table('user')
    op.drop_table('reviewcomments')
    op.drop_table('institution')
    # ### end Alembic commands ###
